import type { Word } from "./words";

/** English spelling for Hebrew speakers — `hint` is the Hebrew meaning. */
export const ENGLISH_WORDS: Record<"easy" | "mid" | "hard", Word[]> = {
  easy: [
    { word: "cat", emoji: "🐱", hint: "חתול" },
    { word: "dog", emoji: "🐶", hint: "כלב" },
    { word: "sun", emoji: "☀️", hint: "שמש" },
    { word: "moon", emoji: "🌙", hint: "ירח" },
    { word: "book", emoji: "📚", hint: "ספר" },
    { word: "ball", emoji: "⚽", hint: "כדור" },
    { word: "fish", emoji: "🐟", hint: "דג" },
    { word: "bird", emoji: "🐦", hint: "ציפור" },
    { word: "tree", emoji: "🌳", hint: "עץ" },
    { word: "car", emoji: "🚗", hint: "מכונית" },
    { word: "hat", emoji: "🎩", hint: "כובע" },
    { word: "bed", emoji: "🛏️", hint: "מיטה" },
    { word: "cup", emoji: "☕", hint: "כוס" },
    { word: "milk", emoji: "🥛", hint: "חלב" },
    { word: "egg", emoji: "🥚", hint: "ביצה" },
    { word: "red", emoji: "🔴", hint: "אדום" },
    { word: "blue", emoji: "🔵", hint: "כחול" },
    { word: "star", emoji: "⭐", hint: "כוכב" },
    { word: "home", emoji: "🏠", hint: "בית" },
    { word: "frog", emoji: "🐸", hint: "צפרדע" },
    { word: "duck", emoji: "🦆", hint: "ברווז" },
    { word: "bear", emoji: "🐻", hint: "דוב" },
    { word: "lion", emoji: "🦁", hint: "אריה" },
    { word: "pig", emoji: "🐷", hint: "חזיר" },
    { word: "cow", emoji: "🐄", hint: "פרה" },
    { word: "bus", emoji: "🚌", hint: "אוטובוס" },
    { word: "cake", emoji: "🎂", hint: "עוגה" },
    { word: "rain", emoji: "🌧️", hint: "גשם" },
    { word: "snow", emoji: "❄️", hint: "שלג" },
    { word: "hand", emoji: "✋", hint: "יד" },
    { word: "eye", emoji: "👁️", hint: "עין" },
    { word: "nose", emoji: "👃", hint: "אף" },
    { word: "door", emoji: "🚪", hint: "דלת" },
    { word: "ship", emoji: "🚢", hint: "ספינה" },
  ],
  mid: [
    { word: "apple", emoji: "🍎", hint: "תפוח" },
    { word: "house", emoji: "🏠", hint: "בית" },
    { word: "water", emoji: "💧", hint: "מים" },
    { word: "green", emoji: "🟢", hint: "ירוק" },
    { word: "yellow", emoji: "🟡", hint: "צהוב" },
    { word: "orange", emoji: "🍊", hint: "תפוז" },
    { word: "flower", emoji: "🌸", hint: "פרח" },
    { word: "school", emoji: "🏫", hint: "בית ספר" },
    { word: "friend", emoji: "👫", hint: "חבר" },
    { word: "mother", emoji: "👩", hint: "אמא" },
    { word: "father", emoji: "👨", hint: "אבא" },
    { word: "sister", emoji: "👧", hint: "אחות" },
    { word: "brother", emoji: "👦", hint: "אח" },
    { word: "banana", emoji: "🍌", hint: "בננה" },
    { word: "bread", emoji: "🍞", hint: "לחם" },
    { word: "horse", emoji: "🐴", hint: "סוס" },
    { word: "tiger", emoji: "🐯", hint: "נמר" },
    { word: "mouse", emoji: "🐭", hint: "עכבר" },
    { word: "chair", emoji: "🪑", hint: "כיסא" },
    { word: "table", emoji: "🪵", hint: "שולחן" },
    { word: "phone", emoji: "📱", hint: "טלפון" },
    { word: "train", emoji: "🚂", hint: "רכבת" },
    { word: "plane", emoji: "✈️", hint: "מטוס" },
    { word: "happy", emoji: "😊", hint: "שמח" },
    { word: "sleep", emoji: "😴", hint: "שינה" },
    { word: "smile", emoji: "😄", hint: "חיוך" },
    { word: "pizza", emoji: "🍕", hint: "פיצה" },
    { word: "candy", emoji: "🍬", hint: "ממתק" },
    { word: "clock", emoji: "⏰", hint: "שעון" },
    { word: "shirt", emoji: "👕", hint: "חולצה" },
  ],
  hard: [
    { word: "elephant", emoji: "🐘", hint: "פיל" },
    { word: "butterfly", emoji: "🦋", hint: "פרפר" },
    { word: "computer", emoji: "💻", hint: "מחשב" },
    { word: "sandwich", emoji: "🥪", hint: "כריך" },
    { word: "birthday", emoji: "🎂", hint: "יום הולדת" },
    { word: "rainbow", emoji: "🌈", hint: "קשת" },
    { word: "teacher", emoji: "👩‍🏫", hint: "מורה" },
    { word: "chicken", emoji: "🐔", hint: "תרנגולת" },
    { word: "kitchen", emoji: "🍳", hint: "מטבח" },
    { word: "morning", emoji: "🌅", hint: "בוקר" },
    { word: "animal", emoji: "🐾", hint: "חיה" },
    { word: "family", emoji: "👨‍👩‍👧‍👦", hint: "משפחה" },
    { word: "window", emoji: "🪟", hint: "חלון" },
    { word: "garden", emoji: "🌻", hint: "גינה" },
    { word: "penguin", emoji: "🐧", hint: "פינגווין" },
    { word: "dolphin", emoji: "🐬", hint: "דולפין" },
    { word: "bicycle", emoji: "🚲", hint: "אופניים" },
    { word: "hospital", emoji: "🏥", hint: "בית חולים" },
    { word: "chocolate", emoji: "🍫", hint: "שוקולד" },
    { word: "umbrella", emoji: "☂️", hint: "מטריה" },
    { word: "strawberry", emoji: "🍓", hint: "תות" },
    { word: "helicopter", emoji: "🚁", hint: "מסוק" },
    { word: "mountain", emoji: "⛰️", hint: "הר" },
    { word: "breakfast", emoji: "🥞", hint: "ארוחת בוקר" },
    { word: "crocodile", emoji: "🐊", hint: "תנין" },
    { word: "pineapple", emoji: "🍍", hint: "אננס" },
    { word: "grandmother", emoji: "👵", hint: "סבתא" },
    { word: "beautiful", emoji: "🌸", hint: "יפה" },
    { word: "together", emoji: "🤝", hint: "יחד" },
    { word: "adventure", emoji: "🧭", hint: "הרפתקה" },
  ],
};
