import type { AvatarSlot } from "../types/models";

export type ShopSection = "enhance" | "avatar";
export type ShopCategory = "cosmetics" | AvatarSlot;
export type ShopItem = {
  id: string;
  emoji: string;
  name: string;
  section: ShopSection;
  category: ShopCategory;
  cost: number;
  desc: string;
  type: "theme" | "avatar";
  effect: "theme" | "equip" | "none";
  consumable?: boolean;
  /** Avatar clothing slot. */
  slot?: AvatarSlot;
};

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: "theme_space",
    emoji: "🚀",
    name: "ערכת חלל",
    section: "enhance",
    category: "cosmetics",
    cost: 350,
    desc: "עיצוב חלל סגול וחלומי",
    type: "theme",
    effect: "theme",
  },
  {
    id: "theme_jungle",
    emoji: "🌴",
    name: "ערכת ג׳ונגל",
    section: "enhance",
    category: "cosmetics",
    cost: 350,
    desc: "עיצוב ג׳ונגל ירוק",
    type: "theme",
    effect: "theme",
  },
  {
    id: "theme_unicorn",
    emoji: "🦄",
    name: "ערכת חד-קרן",
    section: "enhance",
    category: "cosmetics",
    cost: 350,
    desc: "עיצוב קשת ורוד-סגול נוצץ",
    type: "theme",
    effect: "theme",
  },
  {
    id: "avatar_base_kid",
    emoji: "🧒",
    name: "גמד",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 0,
    desc: "הדמות שלכם מההתחלה",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_bunny",
    emoji: "🐰",
    name: "ארנבונה",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 120,
    desc: "אוזניים ארוכות ושן חמודה",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_cat",
    emoji: "🐱",
    name: "חתלתול",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 120,
    desc: "כתום, רך ושובב",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_bear",
    emoji: "🐻",
    name: "דובי",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 150,
    desc: "דוב חום וחמים",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_star",
    emoji: "👽",
    name: "חייזר כוכבים",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 200,
    desc: "הגיע מכוכב רחוק",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_robot",
    emoji: "🤖",
    name: "רובוט",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 250,
    desc: "עיניים זוהרות ואנטנה",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_base_unicorn",
    emoji: "🦄",
    name: "חד-קרן",
    section: "avatar",
    category: "base",
    slot: "base",
    cost: 300,
    desc: "רעמה בצבעי הקשת",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_hat_cap",
    emoji: "🧢",
    name: "כובע מצחייה",
    section: "avatar",
    category: "hat",
    slot: "hat",
    cost: 40,
    desc: "כובע כחול לספורט",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_hat_party",
    emoji: "🥳",
    name: "כובע מסיבה",
    section: "avatar",
    category: "hat",
    slot: "hat",
    cost: 50,
    desc: "מסיבה בכל שלב",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_hat_flowers",
    emoji: "🌸",
    name: "זר פרחים",
    section: "avatar",
    category: "hat",
    slot: "hat",
    cost: 60,
    desc: "פרחים לראש",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_hat_wizard",
    emoji: "🧙",
    name: "כובע קוסם",
    section: "avatar",
    category: "hat",
    slot: "hat",
    cost: 100,
    desc: "עם כוכבים קסומים",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_hat_crown",
    emoji: "👑",
    name: "כתר",
    section: "avatar",
    category: "hat",
    slot: "hat",
    cost: 150,
    desc: "למלכים ומלכות",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_top_shirt",
    emoji: "👕",
    name: "חולצה אדומה",
    section: "avatar",
    category: "top",
    slot: "top",
    cost: 40,
    desc: "חולצה קלאסית",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_top_stripes",
    emoji: "🎽",
    name: "חולצת פסים",
    section: "avatar",
    category: "top",
    slot: "top",
    cost: 50,
    desc: "פסים כחולים",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_top_heart",
    emoji: "💗",
    name: "סוודר לב",
    section: "avatar",
    category: "top",
    slot: "top",
    cost: 70,
    desc: "סוודר ורוד עם לב",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_top_hoodie",
    emoji: "🧥",
    name: "קפוצ׳ון",
    section: "avatar",
    category: "top",
    slot: "top",
    cost: 90,
    desc: "קפוצ׳ון סגול וחם",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_bottom_shorts",
    emoji: "🩳",
    name: "מכנסיים קצרים",
    section: "avatar",
    category: "bottom",
    slot: "bottom",
    cost: 35,
    desc: "לימי קיץ",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_bottom_jeans",
    emoji: "👖",
    name: "ג׳ינס",
    section: "avatar",
    category: "bottom",
    slot: "bottom",
    cost: 50,
    desc: "ג׳ינס כחול",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_bottom_skirt",
    emoji: "👗",
    name: "חצאית נקודות",
    section: "avatar",
    category: "bottom",
    slot: "bottom",
    cost: 50,
    desc: "ורודה עם נקודות",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_shoes_sneakers",
    emoji: "👟",
    name: "נעלי ספורט",
    section: "avatar",
    category: "shoes",
    slot: "shoes",
    cost: 40,
    desc: "לרוץ מהר",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_shoes_rain",
    emoji: "🥾",
    name: "מגפי גשם",
    section: "avatar",
    category: "shoes",
    slot: "shoes",
    cost: 50,
    desc: "לקפוץ בשלוליות",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_shoes_boots",
    emoji: "👢",
    name: "מגפיים",
    section: "avatar",
    category: "shoes",
    slot: "shoes",
    cost: 60,
    desc: "מגפי הרפתקאות",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_extra_balloon",
    emoji: "🎈",
    name: "בלון",
    section: "avatar",
    category: "extra",
    slot: "extra",
    cost: 30,
    desc: "בלון ורוד ביד",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_extra_wand",
    emoji: "🪄",
    name: "שרביט קסמים",
    section: "avatar",
    category: "extra",
    slot: "extra",
    cost: 80,
    desc: "עם כוכב נוצץ",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_extra_pet",
    emoji: "🐶",
    name: "כלבלב",
    section: "avatar",
    category: "extra",
    slot: "extra",
    cost: 120,
    desc: "חבר נאמן לצידכם",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_extra_cape",
    emoji: "🦸",
    name: "גלימת גיבור",
    section: "avatar",
    category: "extra",
    slot: "extra",
    cost: 150,
    desc: "גלימה אדומה",
    type: "avatar",
    effect: "equip",
  },
  {
    id: "avatar_extra_wings",
    emoji: "🧚",
    name: "כנפי פיה",
    section: "avatar",
    category: "extra",
    slot: "extra",
    cost: 180,
    desc: "כנפיים שקופות",
    type: "avatar",
    effect: "equip",
  },
];

export function shopItemById(id: string): ShopItem | undefined {
  return SHOP_ITEMS.find((it) => it.id === id);
}

export function avatarCatalog(): ShopItem[] {
  return SHOP_ITEMS.filter((it) => it.section === "avatar");
}

export function enhanceCatalog(): ShopItem[] {
  return SHOP_ITEMS.filter((it) => it.section === "enhance");
}
