import type { AvatarSlot } from "../types/models";

export type ShopItem = {
  id: string;
  emoji: string;
  name: string;
  slot: AvatarSlot;
  cost: number;
  desc: string;
};

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: "avatar_base_kid",
    emoji: "🧒",
    name: "גמד",
    slot: "base",
    cost: 0,
    desc: "הדמות שלכם מההתחלה",
  },
  {
    id: "avatar_base_bunny",
    emoji: "🐰",
    name: "ארנבונה",
    slot: "base",
    cost: 120,
    desc: "אוזניים ארוכות ושן חמודה",
  },
  {
    id: "avatar_base_cat",
    emoji: "🐱",
    name: "חתלתול",
    slot: "base",
    cost: 120,
    desc: "כתום, רך ושובב",
  },
  {
    id: "avatar_base_bear",
    emoji: "🐻",
    name: "דובי",
    slot: "base",
    cost: 150,
    desc: "דוב חום וחמים",
  },
  {
    id: "avatar_base_star",
    emoji: "👽",
    name: "חייזר כוכבים",
    slot: "base",
    cost: 200,
    desc: "הגיע מכוכב רחוק",
  },
  {
    id: "avatar_base_robot",
    emoji: "🤖",
    name: "רובוט",
    slot: "base",
    cost: 250,
    desc: "עיניים זוהרות ואנטנה",
  },
  {
    id: "avatar_base_unicorn",
    emoji: "🦄",
    name: "חד-קרן",
    slot: "base",
    cost: 300,
    desc: "רעמה בצבעי הקשת",
  },
  {
    id: "avatar_hat_cap",
    emoji: "🧢",
    name: "כובע מצחייה",
    slot: "hat",
    cost: 40,
    desc: "כובע כחול לספורט",
  },
  {
    id: "avatar_hat_party",
    emoji: "🥳",
    name: "כובע מסיבה",
    slot: "hat",
    cost: 50,
    desc: "מסיבה בכל שלב",
  },
  {
    id: "avatar_hat_flowers",
    emoji: "🌸",
    name: "זר פרחים",
    slot: "hat",
    cost: 60,
    desc: "פרחים לראש",
  },
  {
    id: "avatar_hat_wizard",
    emoji: "🧙",
    name: "כובע קוסם",
    slot: "hat",
    cost: 100,
    desc: "עם כוכבים קסומים",
  },
  {
    id: "avatar_hat_crown",
    emoji: "👑",
    name: "כתר",
    slot: "hat",
    cost: 150,
    desc: "למלכים ומלכות",
  },
  {
    id: "avatar_top_shirt",
    emoji: "👕",
    name: "חולצה אדומה",
    slot: "top",
    cost: 40,
    desc: "חולצה קלאסית",
  },
  {
    id: "avatar_top_stripes",
    emoji: "🎽",
    name: "חולצת פסים",
    slot: "top",
    cost: 50,
    desc: "פסים כחולים",
  },
  {
    id: "avatar_top_heart",
    emoji: "💗",
    name: "סוודר לב",
    slot: "top",
    cost: 70,
    desc: "סוודר ורוד עם לב",
  },
  {
    id: "avatar_top_hoodie",
    emoji: "🧥",
    name: "קפוצ׳ון",
    slot: "top",
    cost: 90,
    desc: "קפוצ׳ון סגול וחם",
  },
  {
    id: "avatar_bottom_shorts",
    emoji: "🩳",
    name: "מכנסיים קצרים",
    slot: "bottom",
    cost: 35,
    desc: "לימי קיץ",
  },
  {
    id: "avatar_bottom_jeans",
    emoji: "👖",
    name: "ג׳ינס",
    slot: "bottom",
    cost: 50,
    desc: "ג׳ינס כחול",
  },
  {
    id: "avatar_bottom_skirt",
    emoji: "👗",
    name: "חצאית נקודות",
    slot: "bottom",
    cost: 50,
    desc: "ורודה עם נקודות",
  },
  {
    id: "avatar_shoes_sneakers",
    emoji: "👟",
    name: "נעלי ספורט",
    slot: "shoes",
    cost: 40,
    desc: "לרוץ מהר",
  },
  {
    id: "avatar_shoes_rain",
    emoji: "🥾",
    name: "מגפי גשם",
    slot: "shoes",
    cost: 50,
    desc: "לקפוץ בשלוליות",
  },
  {
    id: "avatar_shoes_boots",
    emoji: "👢",
    name: "מגפיים",
    slot: "shoes",
    cost: 60,
    desc: "מגפי הרפתקאות",
  },
  {
    id: "avatar_extra_balloon",
    emoji: "🎈",
    name: "בלון",
    slot: "extra",
    cost: 30,
    desc: "בלון ורוד ביד",
  },
  {
    id: "avatar_extra_wand",
    emoji: "🪄",
    name: "שרביט קסמים",
    slot: "extra",
    cost: 80,
    desc: "עם כוכב נוצץ",
  },
  {
    id: "avatar_extra_pet",
    emoji: "🐶",
    name: "כלבלב",
    slot: "extra",
    cost: 120,
    desc: "חבר נאמן לצידכם",
  },
  {
    id: "avatar_extra_cape",
    emoji: "🦸",
    name: "גלימת גיבור",
    slot: "extra",
    cost: 150,
    desc: "גלימה אדומה",
  },
  {
    id: "avatar_extra_wings",
    emoji: "🧚",
    name: "כנפי פיה",
    slot: "extra",
    cost: 180,
    desc: "כנפיים שקופות",
  },
];

export function shopItemById(id: string): ShopItem | undefined {
  return SHOP_ITEMS.find((it) => it.id === id);
}
