export type Word = {
  word: string;
  emoji: string;
  hint?: string;
  /** Extra wrong answers for multiple-choice (answer is still `word`). */
  choices?: string[];
};

export const WORDS: Record<"easy" | "mid" | "hard", Word[]> = {
  easy: [
    { word: "כלב", emoji: "🐶" }, { word: "שמש", emoji: "☀️" },
    { word: "ירח", emoji: "🌙" }, { word: "ספר", emoji: "📚" },
    { word: "פרח", emoji: "🌸" }, { word: "לחם", emoji: "🍞" },
    { word: "בית", emoji: "🏠" }, { word: "דוב", emoji: "🐻" },
    { word: "קוף", emoji: "🐒" }, { word: "נחש", emoji: "🐍" },
    { word: "גשם", emoji: "🌧️" }, { word: "גזר", emoji: "🥕" },
    { word: "תות", emoji: "🍓" }, { word: "חתול", emoji: "🐱" },
    { word: "אריה", emoji: "🦁" }, { word: "ארנב", emoji: "🐰" },
    { word: "כוכב", emoji: "⭐" }, { word: "כדור", emoji: "⚽" },
    { word: "ביצה", emoji: "🥚" }, { word: "מטוס", emoji: "✈️" },
    { word: "תפוח", emoji: "🍎" }, { word: "עוגה", emoji: "🎂" },
    { word: "כיסא", emoji: "🪑" }, { word: "שועל", emoji: "🦊" },
    { word: "פרפר", emoji: "🦋" }, { word: "כבשה", emoji: "🐑" },
    { word: "רכבת", emoji: "🚂" }, { word: "חלב", emoji: "🥛" },
    { word: "פיל", emoji: "🐘" }, { word: "סוס", emoji: "🐴" },
    { word: "זאב", emoji: "🐺" }, { word: "פרה", emoji: "🐄" },
    { word: "גמל", emoji: "🐪" }, { word: "שור", emoji: "🐂" },
    { word: "ורד", emoji: "🌹" }, { word: "שלג", emoji: "❄️" },
    { word: "ענן", emoji: "☁️" }, { word: "כוס", emoji: "☕" },
    { word: "אגס", emoji: "🍐" }, { word: "זית", emoji: "🫒" },
    { word: "מים", emoji: "💧" }, { word: "דבש", emoji: "🍯" },
    { word: "ילד", emoji: "👦" }, { word: "שיר", emoji: "🎵" },
    { word: "חול", emoji: "🏖️" }, { word: "זהב", emoji: "🏅" },
    { word: "כרם", emoji: "🍇" }, { word: "ספה", emoji: "🛋️" },
    { word: "חזיר", emoji: "🐷" }, { word: "עכבר", emoji: "🐭" },
    { word: "חמור", emoji: "🫏" }, { word: "שעון", emoji: "⏰" },
    { word: "בלון", emoji: "🎈" }, { word: "פלפל", emoji: "🌶️" },
    { word: "אדום", emoji: "🔴" }, { word: "כחול", emoji: "🔵" },
    { word: "ירוק", emoji: "🟢" }, { word: "צהוב", emoji: "🟡" },
    { word: "צבע", emoji: "🎨" }, { word: "צלחת", emoji: "🍽️" },
    { word: "אפון", emoji: "🫛" }, { word: "כנף", emoji: "🪶" },
  ],
  mid: [
    { word: "ארנבת", emoji: "🐰" }, { word: "ברווז", emoji: "🦆" },
    { word: "צפרדע", emoji: "🐸" }, { word: "קיפוד", emoji: "🦔" },
    { word: "ינשוף", emoji: "🦉" }, { word: "תמנון", emoji: "🐙" },
    { word: "ברבור", emoji: "🦢" }, { word: "ציפור", emoji: "🐦" },
    { word: "כלבלב", emoji: "🐶" }, { word: "גלידה", emoji: "🍦" },
    { word: "לימון", emoji: "🍋" }, { word: "אבטיח", emoji: "🍉" },
    { word: "דולפין", emoji: "🐬" }, { word: "קנגורו", emoji: "🦘" },
    { word: "מכונית", emoji: "🚗" }, { word: "עוגייה", emoji: "🍪" },
    { word: "תרנגול", emoji: "🐓" }, { word: "כדורגל", emoji: "⚽" },
    { word: "שוקולד", emoji: "🍫" }, { word: "מלפפון", emoji: "🥒" },
    { word: "חמנייה", emoji: "🌻" }, { word: "טלפון", emoji: "📱" },
    { word: "ספינה", emoji: "🚢" }, { word: "מטריה", emoji: "☂️" },
    { word: "ריקוד", emoji: "💃" }, { word: "שולחן", emoji: "🪑" },
    { word: "שמיים", emoji: "🌤️" }, { word: "ירקות", emoji: "🥗" },
    { word: "פירות", emoji: "🍓" }, { word: "בגדים", emoji: "👕" },
    { word: "ספרים", emoji: "📖" }, { word: "ילדים", emoji: "👧" },
    { word: "ביצים", emoji: "🥚" }, { word: "נגינה", emoji: "🎶" },
    { word: "ארמון", emoji: "🏰" }, { word: "זיקית", emoji: "🦎" },
    { word: "בקבוק", emoji: "🍶" }, { word: "שחייה", emoji: "🏊" },
    { word: "גשמים", emoji: "🌧️" }, { word: "ורדים", emoji: "🌹" },
    { word: "בננות", emoji: "🍌" }, { word: "עכביש", emoji: "🕷️" },
    { word: "נמרים", emoji: "🐆" }, { word: "פילים", emoji: "🐘" },
    { word: "כרובית", emoji: "🥦" }, { word: "חצילים", emoji: "🍆" },
    { word: "תפוזים", emoji: "🍊" }, { word: "כוכבים", emoji: "⭐" },
    { word: "מוסיקה", emoji: "🎵" }, { word: "ממתקים", emoji: "🍬" },
    { word: "בלונים", emoji: "🎈" }, { word: "גרביים", emoji: "🧦" },
    { word: "מסוקים", emoji: "🚁" }, { word: "כרישים", emoji: "🦈" },
  ],
  hard: [
    { word: "אוטובוס", emoji: "🚌" }, { word: "פנגווין", emoji: "🐧" },
    { word: "עגבנייה", emoji: "🍅" }, { word: "אופניים", emoji: "🚲" },
    { word: "אמבולנס", emoji: "🚑" }, { word: "מכנסיים", emoji: "👖" },
    { word: "משקפיים", emoji: "👓" }, { word: "טלוויזיה", emoji: "📺" },
    { word: "תמנונים", emoji: "🐙" }, { word: "מיקרוגל", emoji: "📡" },
    { word: "ציפורים", emoji: "🐦" }, { word: "מכוניות", emoji: "🚗" },
    { word: "תרנגולת", emoji: "🐔" }, { word: "עכבישים", emoji: "🕷️" },
    { word: "ינשופים", emoji: "🦉" }, { word: "ברווזים", emoji: "🦆" },
    { word: "כלבלבים", emoji: "🐶" }, { word: "חנוכייה", emoji: "🕎" },
    { word: "תמרורים", emoji: "🚦" }, { word: "מיקרופון", emoji: "🎤" },
    { word: "צבעונים", emoji: "🖍️" }, { word: "לחמנייה", emoji: "🥖" },
    { word: "שולחנות", emoji: "🪑" }, { word: "חיפושית", emoji: "🐞" },
    { word: "תמנונות", emoji: "🐙" }, { word: "דינוזאור", emoji: "🦕" },
    { word: "אוקיינוס", emoji: "🌊" }, { word: "מחשבונים", emoji: "🖩" },
    { word: "היפופוטם", emoji: "🦛" }, { word: "פסנתרים", emoji: "🎹" },
    { word: "מנגינות", emoji: "🎶" }, { word: "תלמידים", emoji: "📖" },
  ],
};
